server:
  port: 9005
encrypt:
  key-store:
    location: mytest.jks
    secret: mypass
    alias: mytest
# 若从数据库中获取客户端信息则需配置数据库源
spring:
   datasource:
    url: "jdbc:mysql://localhost:3306/ouath?useUnicode=true&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false"
    username: root
    password: 123456sq
    driver-class-name: com.mysql.jdbc.Driver
