server:
  port: 9007
security:
  oauth2:
    client:
      clientId: app
      clientSecret: app
      userAuthorizationUri: http://localhost:9005/oauth/authorize
      grant-type: password
      scope: app
      access-token-uri: http://localhost:9005/oauth/token
    resource:
      userInfoUri: http://localhost:9005/user
    authorization:
      check-token-access: http://localhost:9005/oauth/check_token
  basic:
    enabled: false
    

logging: 
  config: classpath:logback-boot.xml
    
