spring:
  application:
    name: microservice-consumer-movie-ribbon-with-hystrix
server:
  port: 8010
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 1000
#10秒请求三次如果失败 则打开断路器
hystrix.command.default.circuitBreaker.requestVolumeThreshold: 3
#显示详细信息
management:
  security:
    enabled: false

