server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine3
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
turbine:
  aggregator:
    clusterConfig: default
  appConfig: microservice-consumer-movie-ribbon-with-hystrix3
  clusterNameExpression: "'default'"
logging: 
  level:
    root: INFO
    com.netflix.turbine.monitor: DEBUG